"""Formats review findings and bot metadata into Markdown comment text."""

import json

from code_review_bot.platforms.models import ChangeRequest
from code_review_bot.skill.protocol import Finding, RuntimeMetadata, count_findings_by_severity

BOT_METADATA_PREFIX = "<!-- code-review-bot:"
CODE_REVIEW_BOT_LABEL = "whhe/code-review-bot"
CODE_REVIEW_BOT_URL = "https://github.com/whhe/code-review-bot"

AGENT_DISPLAY_NAMES: dict[str, str] = {
    "claude": "Claude Code",
    "codex": "Codex",
    "opencode": "OpenCode",
}

SEVERITY_LABELS: dict[str, str] = {
    "critical": "Critical",
    "high": "High",
    "medium": "Medium",
    "low": "Low",
}


def format_review_note(
    cr: ChangeRequest,
    skill_name: str,
    skill_version: str,
    fingerprints: list[str],
    summary: str | None = None,
    severity_counts: dict[str, int] | None = None,
    located_count: int = 0,
    unlocated_findings: list[Finding] | None = None,
    resolved_findings: list[Finding] | None = None,
    runtime: RuntimeMetadata | None = None,
) -> str:
    findings = unlocated_findings or []
    counts = severity_counts or count_findings_by_severity(findings)
    lines = [
        "### Code Review",
        "",
        summary or "No significant issues found.",
        "",
        (
            "Severity: "
            f"Critical {counts.get('critical', 0)} / "
            f"High {counts.get('high', 0)} / "
            f"Medium {counts.get('medium', 0)} / "
            f"Low {counts.get('low', 0)}"
        ),
        f"Inline comments posted: {located_count}",
        "",
    ]
    if findings:
        lines.append("#### Findings without diff position (not in this MR's changed lines)")
        lines.append("")
        for finding in findings:
            label = SEVERITY_LABELS.get(finding.severity, finding.severity)
            lines.extend(
                [
                    f"- **[{label}]** `{finding.file_path}:{finding.line_range}`: "
                    f"{finding.description}",
                    f"  - Reason: {finding.reason}",
                ]
            )
        lines.append("")
    if resolved_findings:
        lines.append("#### Previously resolved (not re-reported)")
        lines.append("")
        for finding in resolved_findings:
            label = SEVERITY_LABELS.get(finding.severity, finding.severity)
            lines.append(
                f"- ~~**[{label}]** `{finding.file_path}:{finding.line_range}`: "
                f"{finding.description}~~"
            )
        lines.append("")
    if lines and lines[-1] != "":
        lines.append("")
    lines.append(_format_attribution_line(runtime, skill_version))
    lines.append(_format_runtime_line(runtime))
    metadata = {
        "head_sha": cr.head_sha,
        "skill": skill_name,
        "version": skill_version,
        "fingerprints": sorted(fingerprints),
    }
    lines.append(f"{BOT_METADATA_PREFIX}{json.dumps(metadata, separators=(',', ':'))} -->")
    return "\n".join(lines)


def _format_runtime_line(runtime: RuntimeMetadata | None) -> str:
    model = runtime.model if runtime and runtime.model else "unavailable"
    input_tokens = _format_token_value(runtime.input_tokens if runtime else None)
    output_tokens = _format_token_value(runtime.output_tokens if runtime else None)
    total_tokens = _format_token_value(runtime.total_tokens if runtime else None)
    return (
        f"Model: {model} · Tokens: input {input_tokens} / "
        f"output {output_tokens} / total {total_tokens}"
    )


def _format_attribution_line(runtime: RuntimeMetadata | None, skill_version: str) -> str:
    raw_agent = runtime.agent_type if runtime and runtime.agent_type else "unavailable"
    agent = AGENT_DISPLAY_NAMES.get(raw_agent, raw_agent)
    return (
        f"*Generated by* [*{CODE_REVIEW_BOT_LABEL}*]({CODE_REVIEW_BOT_URL}) "
        f"*· Agent:* *{agent}* *· Skill fingerprint:* *{skill_version}*"
    )


def _format_token_value(value: int | None) -> str:
    if value is None:
        return "unavailable"
    return f"{value:,}"
